
main:
0    start
1    lea   $1, Point
2    call  _new
3    mov   #0, $8
4    mov   #1, 1
5    stw   #1, #0[x]
6    mov   #2, 2
7    stw   #2, #0[y]
8    mov   p1, #0
9    lea   $1, Point
10   call  _new
11   mov   #3, $8
12   mov   #4, 3
13   stw   #4, #3[x]
14   mov   #5, 4
15   stw   #5, #3[y]
16   mov   p2, #3
17   mov   $1, p1
18   mov   $2, p2
19   call  Point.distance_to
20   end

abs:
0    start
1    mov   a, $1
2    blt_i a, 0, @1
3    mov   $8, a
4    jmp   @0
5    lab   @1
6    sub_i $8, 0, a
7    lab   @0
8    end

Point.distance_to:
0    start
1    mov   this, $1
2    mov   other, $2
3    ldw   #0, this[x]
4    ldw   #1, other[x]
5    sub_i $1, #0, #1
6    call  abs
7    mov   #3, $8
8    ldw   #4, this[y]
9    ldw   #5, other[y]
10   sub_i $1, #4, #5
11   call  abs
12   mov   #7, $8
13   add_i $8, #3, #7
14   end