Symbol table [Cat:TYPE:Cat  count:FUNC:(Cat)->Int  ]
STRUCT Cat
   DECL name
      SYMBOL String
   DECL legs
      SYMBOL Int
   DECL eyes
      SYMBOL Int
   Symbol table [name:FIELD:String  legs:FIELD:Int  eyes:FIELD:Int  ]
FUNCTION count
   DECL cat
      SYMBOL Cat
   Symbol table [cat:VAR:Cat  ]
   RETURN
      BINOP + Int
         MEMBER eyes Int
            SYMBOL cat Cat
         MEMBER legs Int
            SYMBOL cat Cat